<?php
include 'conn.php';
require_once('tcpdf_includea2p.php');
ini_set('max_execution_time', 900);

set_time_limit(0);
ini_set('memory_limit', '-1');
error_reporting(0);


class MYPDF extends TCPDF {

	//Page header
	public function Header() {
		  // Get the current page break margin
        $bMargin = $this->getBreakMargin();

        // Get current auto-page-break mode
        $auto_page_break = $this->AutoPageBreak;

        // Disable auto-page-break
        $this->SetAutoPageBreak(false, 0);

        // Define the path to the image that you want to use as watermark.
      
        $this->SetAutoPageBreak($auto_page_break, $bMargin);
		
        // Set the starting point for the page content
        $this->setPageMark();
	 
			//$this->SetFont('helvetica', 'B', 20);
			
			
			
	}
	public function Footer() {
		$ftext='<hr><table border="0" width="100%">
						<tr>
							<td width="40%">'.$_SESSION['login_user'].'</td>
							
							<td width="60%" align="right">Report Generated by PMIS-IT Division &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages().'</td>
						</tr>
						
					</table>';
        // Position at 15 mm from bottom
        $this->SetY(-8);
        // Set font
        $this->SetFont('times', 'I', 10);
        // Page number
		$this->writeHTML($ftext, true, false, true, false, '');
    }
}
// create new PDF document
$pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// set document information
$pdf->SetCreator(PDF_CREATOR);

$pdf->SetTitle('System Login');
$pdf->SetSubject('TCPDF Tutorial');
$pdf->SetKeywords('TCPDF, PDF, example, test, guide');

// set default header data


// set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, 22, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// set some language-dependent strings (optional)
if (@file_exists(dirname(__FILE__).'/lang/eng.php')) {
	require_once(dirname(__FILE__).'/lang/eng.php');
	$pdf->setLanguageArray($l);
}

// ---------------------------------------------------------

// set font
//$pdf->SetFont('dejavusans', '', 15);

// add a page
$pdf->AddPage();
$pdf->SetFont('times', '', 15);
//$pdf->Image('images/image_demo.jpg', 90, 100, 60, 60, '', '', '', true, 72);

	$fp = fopen("../../upload_doc/003-NCB_Bidding_Document.doc", "rb");
	$contents_doc = fread($fp, filesize("upload_doc/003-NCB_Bidding_Document.doc"));
	fclose($fp);
	
	$html='<div>'.$contents_doc.'</div>';
	
	$pdf->writeHTML($html, true, false, true, false, '');	
	$pdf->lastPage();
// ---------------------------------------------------------

//Close and output PDF document
$pdf->Output('System Login.pdf', 'I');

//============================================================+
// END OF FILE
//============================================================+


?>